---
kind: pipeline
name: default

steps:
- name: build-and-test
  image: node:8.6.0
  pull: always
  commands:
   - npm install
   - npm run test:coverage
   - npm run report-coverage

trigger:
  branch:
  - master
  event:
  - pull_request


