---
kind: pipeline
name: default

steps:
- name: restore-cache
  image: plugins/s3-cache
  settings:
    pull: true
    restore: true

- name: build
  image: circleci/node:6.13-browsers
  pull: always
  commands:
   - sudo chown -R circleci:circleci .
   - npm install

- name: save-cache
  image: plugins/s3-cache
  settings:
    pull: true
    rebuild: true
    mount:
      - node_modules
    when:
      event: push   

- name: test
  image: circleci/node:6.13-browsers
  pull: always
  environment:
    CODECOV_TOKEN:
      from_secret: CODECOV_TOKEN
  commands:
   - npm run test:coverage
   - npm run report-coverage

trigger:
  branch:
  - master
  event:
  - pull_request
---
kind: signature
hmac: 6bce0d8194a8e9cfd42bd173f7cdf5969a54496e8aaa10b5532b6f6d765a2009

...
