---
kind: pipeline
name: default

steps:
- name: build-and-test
  image: circleci/node:6.13-browsers
  pull: always
  environment:
#    CODECOV_TOKEN:
#      from_secret: CODECOV_TOKEN
  commands:
   - sudo chown -R circleci:circleci .
   - npm install
   - npm run test:coverage
   # TODO: (suresh) Temporarily disable CodeCov until we provision a new API key.
#   - npm run report-coverage

trigger:
  branch:
    - main
  event:
    - pull_request

---
kind: signature
hmac: 1c489bf8dcfa89d44d2996b8dab25faee0f970c68eb4725b7e8a30f12c23120f

...
