---
# Drone CI pipeline running at: https://drone.cdn-code.org/code-dot-org/blockly/
# 
# Docs here: https://docs.google.com/document/d/1Qls20xfNN6T_DErOMwVQOFJsxAEAdMWFHzBDIbxyUQQ/edit#heading=h.9bln2fv2lgqd
#
# NOTE: after making changes to this file, you'll need to sign them using
# `drone sign code-dot-org/blockly --save`

kind: pipeline
name: default

steps:
- name: build-and-test
  image: circleci/node:6.13-browsers
  pull: always
  environment:
#   CODECOV_TOKEN:
#     from_secret: CODECOV_TOKEN
  commands:
   - sudo chown -R circleci:circleci .
   - npm install
   - npm run test:coverage
   # TODO: (suresh) Temporarily disable CodeCov until we provision a new API key.
#  - npm run report-coverage

trigger:
  branch:
    - main
  event:
    - pull_request

---
kind: signature
hmac: 1ca3082aadd2ccc9f39e5d7c2b2b9c591df7cda9cbf02b6606c33ebd0453885f

...
