version: 2
jobs:
  build:
    working_directory: ~/code-dot-org/blockly
    parallelism: 1
    docker:
    - image: circleci/node:6.13
    steps:
    - checkout
    - restore_cache:
        keys:
        - v2-dep-{{ .Branch }}-
        - v2-dep-staging-
        - v2-dep-
    - run: npm install
    - save_cache:
        key: v1-dep-{{ .Branch }}-{{ epoch }}
        paths:
        - ./node_modules
    - run: npm test
